name: DPets
version: 1.1.5
main: me.firebreath15.dpets.DPets
author: FireBreath15
commands:
  pet:
    description: Donor Pets Main Command
    usage: /pet <redeem|(username)> [type]
    permission: dpets.pet
    permission-message: No permission!
  dpets:
    description: Donor Pets Main Command
    usage: /dpets <redeem|(username)> [type]
    permission: dpets.pet
    permission-message: No permission!
permissions:
  dpets.pet:
    default: true
  dpets.dpets:
    default: true
  dpets.give:
    default: op