#For use with WorldGuard 6.0.0-Beta02 and WorldEdit 5.6.3. As of December 4, 2014.
name: DPets
version: 1.1.9
main: me.firebreath15.dpets.DPets
author: FireBreath15
depend: [WorldEdit, WorldGuard]
commands:
  pet:
    description: Donor Pets Main Command
    usage: /pet <redeem|(username)> [type]
    permission: dpets.pet
    permission-message: No permission!
  dpets:
    description: Donor Pets Main Command
    usage: /dpets <redeem|(username)> [type]
    permission: dpets.pet
    permission-message: No permission!
permissions:
  dpets.pet:
    default: true
  dpets.dpets:
    default: true
  dpets.give:
    default: op